In [1]:
import numpy as np

In [2]:
myList = [1, 2, 3]

In [3]:
type(myList)

list

In [4]:
arr = np.array(myList)

In [5]:
type(arr)

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix.shape

(3, 3)

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# Broadcasting
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [11]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(10)

array([0.75873783, 0.79297608, 0.7190313 , 0.81395071, 0.62771569,
       0.66551106, 0.5061646 , 0.00506131, 0.82700215, 0.94947216])

In [14]:
np.random.randn(10)

array([-1.65062173, -0.40113774, -1.12361614,  0.85862514,  0.62924869,
       -0.28084459, -1.12637904,  0.11008613,  0.58569988,  1.70231569])

In [15]:
np.random.normal()

0.16319903570187735

In [16]:
np.random.randint(1, 100, 10)

array([30, 46, 40, 16,  9, 19, 89, 82, 11, 76])

In [17]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [18]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
randarr = np.random.randint(0, 50, 10)
randarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [20]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
randarr.max()

47

In [22]:
randarr.min()

0

In [23]:
randarr.argmax()

0

In [24]:
randarr.argmin()

7

In [25]:
randarr.dtype

dtype('int64')