In [1]:
import numpy as np

In [2]:
myList = [1, 2, 3]

In [3]:
type(myList)

list

In [4]:
arr = np.array(myList)

In [5]:
type(arr)

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix.shape

(3, 3)

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
# Broadcasting
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [19]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(10)

array([0.25591959, 0.08446653, 0.95855395, 0.05470017, 0.29932852,
       0.29583213, 0.73548778, 0.13139559, 0.62095579, 0.61544247])

In [26]:
np.random.randn(10)

array([-1.27136657,  0.81271794,  0.69203493, -2.40513437,  0.23993173,
       -1.19428797,  0.28388589,  1.33105671,  0.74947127,  0.79623345])

In [27]:
np.random.normal()

-0.7330827727170218

In [28]:
np.random.randint(1, 100, 10)

array([80, 79,  1, 22, 61,  8, 19, 45, 16, 48])

In [30]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
randarr = np.random.randint(0, 50, 10)
randarr

array([12, 29, 40, 49, 19, 47,  8, 29, 34, 44])

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])